question_data =  [
                         {"category": "Science & Nature",
                          "type": "boolean",
                          "difficulty": "easy",
                          "question": "Igneous rocks are formed by excessive heat and pressure.",
                          "correct_answer": "False",
                          "incorrect_answers": ["True"]},
                         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                          "question": "Arcade Fire&#039;s &#039;The Suburbs&#039; won the Album of the Year award in "
                                      "the 2011 Grammys.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "Geography", "type": "boolean", "difficulty": "easy",
                          "question": "The Republic of Malta is the smallest microstate worldwide.",
                          "correct_answer": "False",
                          "incorrect_answers": ["True"]},
                         {"category": "History", "type": "boolean", "difficulty": "easy",
                          "question": "The Spitfire originated from a racing plane.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "Politics", "type": "boolean", "difficulty": "easy",
                          "question": "The S in Harry S. Truman stands for &quot;Samuel&quot;.",
                          "correct_answer": "False",
                          "incorrect_answers": ["True"]},
                         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                          "question": "The colour of the pills in the Matrix were Blue and Yellow.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
                         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
                          "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by "
                                      "the nickname Kyon.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                          "question": "&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said "
                                      "within the Conan Doyle books of Sherlock Holmes.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
                          "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two "
                                      "characters: a miniboss named Yakon and Kid Buu.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "Geography", "type": "boolean", "difficulty": "medium",
                          "question": "Liechtenstein does not have an airport.", "correct_answer": "True",
                          "incorrect_answers": ["False"]},
                         {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                          "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
                          "incorrect_answers": ["True"]},
                         {"category": "Sports", "type": "boolean", "difficulty": "easy",
                          "question": "In association football, or soccer, a corner kick is when the game restarts "
                                      "after someone scores a goal.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
                         {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
                          "question": "Nickelodeon rejected the pilot to Adventure Time.", "correct_answer": "True",
                          "incorrect_answers": ["False"]},
                         {"category": "History", "type": "boolean", "difficulty": "hard",
                          "question": "The USS Missouri (BB-63) last served in the Korean War.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
                         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                          "question": "In &quot;Super Mario World&quot;, the rhino mini-boss, Reznor, is named after "
                                      "the lead singer of the band &quot;Nine Inch Nails&quot;.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                          "question": "The scientific name for the Southern Lights is Aurora Australis?",
                          "correct_answer": "True",
                          "incorrect_answers": ["False"]},
                         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                          "question": "Musical artist, Future, collaborated with Kendrick Lamar for the song: "
                                      "&quot;Mask Off&quot;.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "Sports", "type": "boolean", "difficulty": "medium",
                          "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have "
                                      "been used in matches.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                          "question": "The video game &quot;Fuel&quot; has an open world that is 5,560 square miles?",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                          "question": "Shang Tsung is a playable character in Mortal Kombat XL.",
                          "correct_answer": "False",
                          "incorrect_answers": ["True"]}]
